import { experimentDto } from "./core/experimentDto"
import { AnalysisType } from "./core/enums"

export let experimentDtos: experimentDto[] = [
    {
        Id : 1,
        Name: "entitySpace1",
        Type: AnalysisType.EntitySpace,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 2,
        Name: "entityView",
        Type: AnalysisType.EntityView,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 3,
        Name: "entityGraph",
        Type: AnalysisType.Graph,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 4,
        Name: "entitySpace1",
        Type: AnalysisType.EntitySpace,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 5,
        Name: "entityView",
        Type: AnalysisType.EntityView,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 6,
        Name: "entityGraph",
        Type: AnalysisType.Graph,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 7,
        Name: "entitySpace1",
        Type: AnalysisType.EntitySpace,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 8,
        Name: "entityView",
        Type: AnalysisType.EntityView,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 9,
        Name: "entityGraph",
        Type: AnalysisType.Graph,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 10,
        Name: "entitySpace1",
        Type: AnalysisType.EntitySpace,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 11,
        Name: "entityView",
        Type: AnalysisType.EntityView,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 3,
        Name: "entityGraph",
        Type: AnalysisType.Graph,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },{
        Id : 12,
        Name: "entitySpace1",
        Type: AnalysisType.EntitySpace,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 13,
        Name: "entityView",
        Type: AnalysisType.EntityView,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 14,
        Name: "entityGraph",
        Type: AnalysisType.Graph,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 15,
        Name: "entitySpace1",
        Type: AnalysisType.EntitySpace,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 16,
        Name: "entityView",
        Type: AnalysisType.EntityView,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 17,
        Name: "entityGraph",
        Type: AnalysisType.Graph,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 18,
        Name: "entitySpace1",
        Type: AnalysisType.EntitySpace,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 19,
        Name: "entityView",
        Type: AnalysisType.EntityView,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 20,
        Name: "entityGraph",
        Type: AnalysisType.Graph,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 21,
        Name: "entitySpace1",
        Type: AnalysisType.EntitySpace,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 22,
        Name: "entityView",
        Type: AnalysisType.EntityView,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 23,
        Name: "entityGraph",
        Type: AnalysisType.Graph,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 24,
        Name: "entitySpace1",
        Type: AnalysisType.EntitySpace,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    },
    {
        Id : 25,
        Name: "entityView",
        Type: AnalysisType.EntityView,
        CreatedBy: "jixge" ,
        UpdatedBy: "jixge" ,
        EntitySpaceName: "xingfeed",
        EntitySpaceUrl: "",
        EntityViewName: "xingFeedview",
        EntityViewUrl: "",
        CustomerId: "Satori",
        CustomerEnv: "Sources"
    }
]